version: '2'
services:
 nginx:
  image: webdevops/php-nginx:latest
  container_name: nginx-server
  ports:
  - 80:80
  - 443:443
  volumes:
  - /var/www:/app
  - /root/dockerstacks/wtnz-docker/vhost.conf:/opt/docker/etc/nginx/vhost.conf
  - /root/dockerstacks/wtnz-docker/wtnz.conf:/opt/docker/etc/nginx/vhost.common.d/wtnz.conf
  - /etc/letsencrypt/live/${HOST_NAME}.${DOMAIN_NAME}/cert.pem:/opt/docker/etc/nginx/ssl/server.crt
  - /etc/letsencrypt/live/${HOST_NAME}.${DOMAIN_NAME}/privkey.pem:/opt/docker/etc/nginx/ssl/server.key
  restart: always
  environment:
  - PHP_DISPLAY_ERRORS=1
 socketio:
  build: ./customBuilds/wtnz-socketio
  image: amphaal/wtnz-socketio:latest
  container_name: socketio-server
  ports:
  - 3000:3000
  volumes:
  - /var/www/wtnz/users_data:/srv/users_data
  - /var/www/socketnz/app.js:/srv/app.js
  - /etc/letsencrypt/live/${HOST_NAME}.${DOMAIN_NAME}/cert.pem:/srv/server.crt
  - /etc/letsencrypt/live/${HOST_NAME}.${DOMAIN_NAME}/privkey.pem:/srv/server.key
  restart: always
